[package]
name = "rendlessh"
version = "0.1.0"
authors = ["lafolle <fghjklp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol = "1.2.1"
futures-lite = "1.7.0"
